#   message.yaml
# Конфигурация для работы с сообщениями,
# высвечивающимися пользователям.

# Тестовая секция для модуля Examples.
messages:
  hello: |
    Добрый день или вечер, дружище 👋!
    Как твои дела, братан?
# Секция для модуля Roll.
roll:
  # win предполагает высвечивание после броска.
  # - {0} - число выпадаемых очков;
  # - {1} - нынешнее (!) число монет;
  # - {2} - нынешнее (!) число бросков.
  win: |
    Вам выпало {0} очка(-ов) 🎲!
    У вас теперь {1} монет 💰
    Теперь у Вас осталось {2} бросков 😔...
  # notEnough предполагает высвечивание в случае,
  # если у пользователя недостаточно бросков в
  # инвентаре.
  notEnough: |
    У вас недостаточно бросков 😔...