#   message.yaml
# Конфигурация для работы с сообщениями,
# высвечивающимися пользователям.

# Тестовая секция для модуля Examples.
messages:
  hello: |
    Добрый день или вечер, дружище 👋!
    Как твои дела, братан?
# Секция для модуля Roll.
roll:
  # win предполагает высвечивание после броска.
  # - {0} - число выпадаемых очков;
  # - {1} - нынешнее (!) число монет;
  # - {2} - нынешнее (!) число бросков.
  win: |
    Вам выпало {0} очка(-ов) 🎲!
    У вас теперь {1} монет 💰
    Теперь у Вас осталось {2} бросков.
  # notEnough предполагает высвечивание в случае,
  # если у пользователя недостаточно бросков в
  # инвентаре.
  notEnough: |
    У вас недостаточно бросков 😔...
# Секция для модуля Promocode
promocode:
  # sucsess предполагает высвечивание после успешной активации.
  # - {0} - количество валюты;
  # - {1} - наименование валюты;
  # - {2} - нынешнее (!) количество валюты.
  sucsess: |
    Успешная активация!
    Вам начисленно {0} {1}!
    Теперь у вас {2} {1}
  # notFound предполагает высвечивание в случае,
  # если промокода не существовало никогда
  notFound: |
    К сожалению этого промокода не существует :(
    Чтобы получать промокоды подпишитесь на наши каналы, а так же смотрите стримы наших стримеров!
  # express предполагает высвечивание в случае,
  # если срок действия промо истёк
  express: |
    К сожалению срок действия этого промокода закончился :(
    Чтобы не пропускать актуальные промокоды, подпишитесь на наши каналы, а так же смотрите стримы наших стримеров!
  # noActivations предполагает высвечивание в случае,
  # если у промокода закончились активации
  noActivations: |
    К сожалению у этого промокода не осталось активаций :(
    Чтобы активировать промокоды самым первым, подпишитесь на наши каналы, а так же смотрите стримы наших стримеров!
  # used предполагает высвечивание в случае,
  # если пользователь уже использовал промокд
  used: |
    Вы уже использовали этот промокод :(
    Что бы получать новые промокоды, подпишитесь на наши каналы, а так же смотрите стримы наших стримеров!
# Секция для модуля Queue
queue:
  giveCodeMessage: |
    Вы вставали в очередь и это принесло плоды: забирайте код!
  giveCodeButton: |
    Забрать код...
  putQueue: |
    Вы были поставлены в очередь... Ожидайте...
start:
  startUser: |
    🫡Привет, {0}!

    Это бот-кубик. Здесь нельзя проиграть, тут каждый получает свою луну за активность!

    Все просто: крути кубик 🎲 , собирай доп.броски 🎯 , приглашай друзей 🙋 и попробуй наши-мини игры 🎰 !

    Если есть вопросы - загляни в ❓ FAQ. Если обнаружил проблему - обратная связь. 

    Твой баланс: {1} 💰
    Твои броски: {2} 🎲
    👑 Подписка: {3}
  faq_btn: |
    ❓ FAQ
  addroll_btn: |
    🎯 Доп. Броски
  profile_btn: |
    🎒 Профиль
  mini_games_btn: |
    🎰 Мини-игры
  withdraw_btn: |
    🚀Вывод предметов
  subscribe_btn: |
    👑 Подписка
  shopGD_btn: |
    💚 Магазин гемов
ref:
  sucsessRef: |
    Поздравляем  с регестрацией в нашем кубик-боте
    За ваше приглашение вы получаете 100 монеток!
  newRef: |
    У вас новый реферал!
    {0} зарегестрировался по вашей ссылке, вам начислен 1 бросок!
  createRefLink: |
    Ваша реферальная ссылка создана!
    Отправте её своим друзьям 
    {0}
  noRefLink: |
    У вас ещё нет реферальной ссылки
    Нажмите на кнопку ниже, чтобы создать её!
  newLink_btn: |
    Создать
  myRefs: |
    Ваши рефералы:
    {0}
  noRefs: |
    У вас пока нет рефералов
faq:
  global: |
    ❓ F.A.Q. Кубика-бота.

    Общие понятия и условия: 

    Данный бот создан исключительно в развлекательных целях. Цель крайне проста - кидай кубик, играй в мини-игры и зарабатывай монетки 💰 , чтобы получить свою луну!

    Более подробно мы расписали здесь: https://t.me/cube_updates/166

    Данная задумка и авторские права принадлежат каналу @genshinnothing

    Полезные ссылки:
    @cube_updates - канал, где будут выходить новости об обновлениях, тех.работах, устранению ошибок, а так же заметки разработчика
    @GameNothingsupport_bot - тех. поддержка бота по различным вопросам
    @genshinnothing - наш канал, где будем выкладывать промокоды и полезные новости по Genshin Impact

    Реклама и участие канала в 🎯Доп.Бросках
    @nothingtg - Владелец 🥷
  mini_games: |
    Это FAQ по мини играм, тут про то что есть кейсы и онлайн
  online: |
    Это FAQ по онлайну
  cases: |
    Это FAQ по кейсам
  ref: |
    Это FAQ по рефералам 
  mini_games_btn: |
    Мини-игры
  ref_btn: |
    Рефералка
  cases_btn: |
    Кейсы
  online_btn: |
    Оналйн
addrolls: 
  main: |
    Здесь список наших спонсоров. ✍️ Подписка на каждый канал дают по 1 доп.броску 🎯
  sub_btn: |
    Подписаться
  allreadySub: |
    Вы уже подписаны на этот канал
  subsReqwest: |
    Подпишитесь на {0}, чтобы получить 1 бросок!
  allCollected: |
    Вы уже собрали все броски на сегодня!
    Возвращайтесь завтра!
  noSubs: |
    Подпишитесть на все каналы чтобы собрать максимум бросков!
  sucsess: |
    Успешно! Начислено {0} бросков!

    Скорее Кидай кубик 🎲 , потому что броски нельзя накопить!
  collect_btn: |
    ➕ Собрать броски 
  home: |
    🏠 Домой
profile:
  menu: |
    {0}, вот, что у тебя есть:
    Получено: {1} 💰
    Всего бросков: {2} 🎲
    Открытые кейсы: {3}
    Дней в кубике: {4}
    Победы в сражениях: {5}

    Твои предметы:
    60 гемов: {6} (пока доступно для возвышения или крафта)
    Луна: {7}
    1090 гемов: {8}
  inv: |
    Это инвентарь
  inv_btn: |
    Инвентарь
  ref_btn: |
    Рефералка