#   message.yaml
# Конфигурация для работы с сообщениями,
# высвечивающимися пользователям.

# Тестовая секция для модуля Examples.
messages:
  hello: |
    Добрый день или вечер, дружище 👋!
    Как твои дела, братан?
# Секция для модуля Roll.
roll:
  # win предполагает высвечивание после броска.
  # - {0} - число выпадаемых очков;
  # - {1} - нынешнее (!) число монет;
  # - {2} - нынешнее (!) число бросков.
  win: |
    Вам выпало {0} очка(-ов) 🎲!
    У вас теперь {1} монет 💰
    Теперь у Вас осталось {2} бросков.
  # notEnough предполагает высвечивание в случае,
  # если у пользователя недостаточно бросков в
  # инвентаре.
  notEnough: |
    У вас недостаточно бросков 😔...
# Секция для модуля Promocode
promocode:
  # sucsess предполагает высвечивание после успешной активации.
  # - {0} - количество валюты;
  # - {1} - наименование валюты;
  # - {2} - нынешнее (!) количество валюты.
  sucsess: |
    Успешная активация!
    Вам начисленно {0} {1}!
    Теперь у вас {2} {1}
  # notFound предполагает высвечивание в случае,
  # если промокода не существовало никогда
  notFound: |
    К сожалению этого промокода не существует :(
    Чтобы получать промокоды подпишитесь на наши каналы, а так же смотрите стримы наших стримеров!
  # express предполагает высвечивание в случае,
  # если срок действия промо истёк
  express: |
    К сожалению срок действия этого промокода закончился :(
    Чтобы не пропускать актуальные промокоды, подпишитесь на наши каналы, а так же смотрите стримы наших стримеров!
  # noActivations предполагает высвечивание в случае,
  # если у промокода закончились активации
  noActivations: |
    К сожалению у этого промокода не осталось активаций :(
    Чтобы активировать промокоды самым первым, подпишитесь на наши каналы, а так же смотрите стримы наших стримеров!
  # used предполагает высвечивание в случае,
  # если пользователь уже использовал промокд
  used: |
    Вы уже использовали этот промокод :(
    Что бы получать новые промокоды, подпишитесь на наши каналы, а так же смотрите стримы наших стримеров!
# Секция для модуля Queue
queue:
  giveCodeMessage: |
    Вы вставали в очередь и это принесло плоды: забирайте код!
  giveCodeButton: |
    Забрать код...
  putQueue: |
    Вы были поставлены в очередь... Ожидайте...
start:
  startUser: |
    Привет {0}!
    Крути кубик и бла-бла-бла
    Подписка: {1}
ref:
  sucsessRef: |
    Поздравляем  с регестрацией в нашем кубик-боте
    За ваше приглашение вы получаете 100 монеток!
  newRef: |
    У вас новый реферал!
    {0} зарегестрировался по вашей ссылке, вам начислен 1 бросок!
  createRefLink: |
    Ваша реферальная ссылка создана!
    Отправте её своим друзьям 
    {0}
  noRefLink: |
    У вас ещё нет реферальной ссылки
    Нажмите на кнопку ниже, чтобы создать её!
  myRefs: |
    Ваши рефералы:
    {0}
  noRefs: |
    У вас пока нет рефералов
