#   prizes.yaml
# Конфигурация, требуемая при работе с модулем
# Roll. Каждая секция в rolls является призом.
#
# - в скобках секции указано число, за выпадение
#   которого выдаётся приз;
# - в type указан параметр инвентаря, по которому
#   выдаётся приз;
# - в value указано значение, выдаваемое в качестве
#   приза.
rolls:
  (1):
    type: 'coins'
    value: 1
  (2):
    type: 'coins'
    value: 5
  (3):
    type: 'coins'
    value: 10
  (4):
    type: 'coins'
    value: 15
  (5):
    type: 'coins'
    value: 20
  (6):
    type: 'coins'
    value: 25